// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCugonnABpppVrSip9wHe1H-tbLrSgzsaM',
    appId: '1:170279400561:web:76e979a62cb9e8c22c57d0',
    messagingSenderId: '170279400561',
    projectId: 'cinerate-projet-flutter',
    authDomain: 'cinerate-projet-flutter.firebaseapp.com',
    storageBucket: 'cinerate-projet-flutter.firebasestorage.app',
    measurementId: 'G-KL2RLSRFB7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGWKZ3lZ9Pwlz0AmzKw0ehLOM6Z1WzxHk',
    appId: '1:170279400561:ios:9e4a6e35535428e52c57d0',
    messagingSenderId: '170279400561',
    projectId: 'cinerate-projet-flutter',
    storageBucket: 'cinerate-projet-flutter.firebasestorage.app',
    iosBundleId: 'be.mobile.nicolaschen.cinerate.cinerate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGWKZ3lZ9Pwlz0AmzKw0ehLOM6Z1WzxHk',
    appId: '1:170279400561:ios:9e4a6e35535428e52c57d0',
    messagingSenderId: '170279400561',
    projectId: 'cinerate-projet-flutter',
    storageBucket: 'cinerate-projet-flutter.firebasestorage.app',
    iosBundleId: 'be.mobile.nicolaschen.cinerate.cinerate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCugonnABpppVrSip9wHe1H-tbLrSgzsaM',
    appId: '1:170279400561:web:76e979a62cb9e8c22c57d0',
    messagingSenderId: '170279400561',
    projectId: 'cinerate-projet-flutter',
    authDomain: 'cinerate-projet-flutter.firebaseapp.com',
    storageBucket: 'cinerate-projet-flutter.firebasestorage.app',
    measurementId: 'G-KL2RLSRFB7',
  );
}
